services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=moisesm
      - MYSQL_PASSWORD=Mdvlinux23
      - MYSQL_DATABASE=test

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: Mdvlinux23
      MYSQL_DATABASE: test
      MYSQL_USER: moisesm
      MYSQL_PASSWORD: Mdvlinux23
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
